## Data-X (IEOR 290): HW 1

### Uvika Chaturvedi

#### SID: 3032162420

# Problem 1

In [53]:
#importing libraries
import numpy as np

In [22]:
#Creating two numpy arrays
a = np.arange(10,20)
b = np.linspace(1, 7, num=10)

In [54]:
#Squaring all the elements
a_squared = np.square(a)
b_squared = np.square(b)

#Adding the squared arrays
summation = a_squared + b_squared

#Sum of even elements
sum_even_elements = sum(summation[::2])

#Square root of the added array
square_root = np.sqrt(summation)


In [31]:
#Printing the appended matrix (m)
m = np.append(a,b).reshape(5,4)
m

array([[ 10.        ,  11.        ,  12.        ,  13.        ],
       [ 14.        ,  15.        ,  16.        ,  17.        ],
       [ 18.        ,  19.        ,   1.        ,   1.66666667],
       [  2.33333333,   3.        ,   3.66666667,   4.33333333],
       [  5.        ,   5.66666667,   6.33333333,   7.        ]])

In [38]:
#Print the second and third column of the m matrix (m2)
m2 = m[:,1:3]
m2

array([[ 11.        ,  12.        ],
       [ 15.        ,  16.        ],
       [ 19.        ,   1.        ],
       [  3.        ,   3.66666667],
       [  5.66666667,   6.33333333]])

In [39]:
# Printing the dot product of transpose of m2 and m (m3)
m3 = np.dot(np.transpose(m2),m)
m3

array([[ 697.33333333,  748.11111111,  437.88888889,  482.33333333],
       [ 402.22222222,  437.88888889,  454.55555556,  489.88888889]])

In [40]:
#Rounding the elements of m3 to 2 decimal places
m3 = np.around(m3,decimals = 2)
m3

array([[ 697.33,  748.11,  437.89,  482.33],
       [ 402.22,  437.89,  454.56,  489.89]])

In [52]:
#Sorting m3 into descending order
m3 = np.sort(m3,axis = -1)[::-1].reshape(2,4)
m3

array([[ 748.11,  697.33,  489.89,  482.33],
       [ 454.56,  437.89,  437.89,  402.22]])